// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7f-Ae94t5LqgDmUkO2ISMKh5YoHKPYhw',
    appId: '1:71842554553:web:7718fb1b88bec3e0927168',
    messagingSenderId: '71842554553',
    projectId: 'smart-trip-planner-fc329',
    authDomain: 'smart-trip-planner-fc329.firebaseapp.com',
    storageBucket: 'smart-trip-planner-fc329.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDesq9IomA3LJcZUBfJo6Cjoa7XF_SKh-8',
    appId: '1:71842554553:android:fe910374721d6e5e927168',
    messagingSenderId: '71842554553',
    projectId: 'smart-trip-planner-fc329',
    storageBucket: 'smart-trip-planner-fc329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOw83qMLqxiwbJryoRT71uihSXsLQ9gk',
    appId: '1:71842554553:ios:7ddfab8494065d0d927168',
    messagingSenderId: '71842554553',
    projectId: 'smart-trip-planner-fc329',
    storageBucket: 'smart-trip-planner-fc329.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOw83qMLqxiwbJryoRT71uihSXsLQ9gk',
    appId: '1:71842554553:ios:7ddfab8494065d0d927168',
    messagingSenderId: '71842554553',
    projectId: 'smart-trip-planner-fc329',
    storageBucket: 'smart-trip-planner-fc329.firebasestorage.app',
    iosBundleId: 'com.example.smartTripPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7f-Ae94t5LqgDmUkO2ISMKh5YoHKPYhw',
    appId: '1:71842554553:web:083867a5155b4f8a927168',
    messagingSenderId: '71842554553',
    projectId: 'smart-trip-planner-fc329',
    authDomain: 'smart-trip-planner-fc329.firebaseapp.com',
    storageBucket: 'smart-trip-planner-fc329.firebasestorage.app',
  );
}
